### ISSUE TITLE
Compiliation Errors

### ISSUE THREAD

**Issue by MeikelLP** [shadowmint/unity-n-input#1]
I have [C#7](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src) installed. But even without these errors occur.

`Assets\packages\n-input\experimental\IInput.cs(5,20): error CS0246: The type or namespace name 'InputMap' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\packages\n-input\lib\templates\isometric\experimental\ExperimentalIsoActor.cs(50,26): error CS0513: 'ExperimentalIsoActor.OnMotionChange(GenericMotionEvent)' is abstract but it is contained in non-abstract class 'ExperimentalIsoActor'`
`Assets\packages\n-input\lib\templates\isometric\experimental\ExperimentalIsoInput.cs(5,39): error CS0535: 'ExperimentalIsoInput' does not implement interface member 'IInput.Configure(InputMap)'`

**Comment by shadowmint** [comment]
Sorry, must've left some experimental stuff on master. Fixed now.

In general master is unstable on most of my repos; if you want a working version, look in the tags and install the latest one, eg. `npm install --save shadowmint/unity-n-input#2.0.0`
